# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88b8cd4f6a25803bd3c867bb90daa510076688ec2eb1b587519781c19363815b47aaa29d84746536edfb642121d761c88ad0bade7830ca15b95683111663c4f4

test:
  secret_key_base: a6bbe81db4e9193de36d181eb0fc622fdebcaf52d633bd34e186f3660906eca3cc7fefe523e112224b24d7d53ad649af26301a09a42ef9adb5d8e73075c2501f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
